// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package infrastructure

import (
	"github.com/google/wire"
	"github.com/traPyojobot/traPyojo/interface/handler"
	"github.com/traPyojobot/traPyojo/interface/repository"
	"github.com/traPyojobot/traPyojo/usecase/service"
)

// Injectors from wire.go:

func InjectAPIServer() (handler.API, error) {
	tweetRepository := repository.NewTweetRepository()
	tweetService := service.NewTweetService(tweetRepository)
	tweetHandler := handler.NewTweetHandler(tweetService)
	api := handler.NewAPI(tweetHandler)
	return api, nil
}

// wire.go:

var tweetSet = wire.NewSet(
	NewTwitterAPI, repository.NewTweetRepository, service.NewTweetService,
)

var apiSet = wire.NewSet(handler.NewTweetHandler, handler.NewAPI)
